### PR TITLE
Stateful, fast renderer for MMCoreTextView

### LINKED ISSUE #796: Scrolling performance regression using intermediate NSImage
I'm filing this issue to track the known scrolling performance regression from #757 (see that thread for more details).  Although it's known already, this way I can subscribe to the issue and hopefully get notified when it's fixed. :)

### PR DESCRIPTION
**Pull request by s4y**
This change replaces the current rendering paths in `MMCoreTextView` with one which draws from an array of structs that represent the state of each character cell. It applies draw commands to the array
and marks any touched cells as needing display instead of drawing to a view or image buffer.

In my own tests, this renderer seems to be roughly twice as fast of the current one. Because it seems to work for the use cases of all of the current renderers and reused a lot of code, this PR replaces the other paths instead of adding a preference.

Fixes #796.

### CODE REVIEW

**Comment by amadeus** [comment]
One small thing I noticed with this latest version, fonts are a bit thinner:

example

I guess visually I prefer the thicker looking fonts, but I realize it's kinda been a re-occuring thing with Mojave that font rendering has thinned up a bit, and might just be what I need to get used too now?

**Comment by ychin** [comment]
I haven't had time to look into the PR yet, but thinner text is usually a sign that the font smoothing / subpixel rendering (which is deprecated in Mojave) isn't properly configured.

Also, I think we may want to make sure to runs faster than the 10.13 pre-Mojave renderer if we are going to remove that. I have checked out other similar types of renderer before and they don't usually perform faster than the native `scrollRect:` implementation if we are updating the texts in software.

**Comment by juliuszint** [comment]
When started from the commandline a new line is output to standard out. 

The issue mentioned here https://github.com/macvim-dev/macvim/issues/796#issuecomment-464307565 was also present in MacVim before. 

As for performance i am using it on a 4k external Monitor on a MacBook Pro 15-inch 2017 and it seems just as fast as the old renderer if not faster. Obviously this is just my perception if there are any profiling methods let me know.

**Comment by juliuszint** [comment]
NERDTree in combination with vim-devicons works almost perfect, except for the rendering issue on the cursor line, where the folder icon gets clipped.
screenshot 2019-02-19 at 09 53 31

**Comment by chdiza** [comment]
If it's going to make fonts look bad (thin, faint) on non-retina monitors, then there should be a preference to turn this new renderer on or off.

**Comment by ychin** [comment]
@chdiza I think the bar is this renderer wouldn’t degrade rendering. It’s been on my todo list to take a screenshot and do unit tests against known rendering results but it’s tricky to do it right.

**Comment by s4y** [comment]
@chdiza The mystery font rendering change is a bug; I noticed it but haven’t had a chance to track it down yet. Please keep hunting for bugs if possible!

@ychin If the performance isn’t good enough, note that my next move will be to use separate movable `CALayers` in the scroll region. Only new lines are rendered during scrolling, which should be blazing fast. This plays nicely with the macOS compositor and is how browsers scroll — I think it’s a pretty optimal choice. (It could even enable things like per-split smooth scrolling…)

If performance is an issue with this PR, I could add that now instead of holding off.

**Comment by s4y** [comment]
@juliuszint Thanks! I don’t use any plugins that insert images. Now I’ve got one to try.

**Comment by amadeus** [comment]
Ok - I did find some pretty serious bugs. I normally use Source Code Pro as my main font, but I was messing around with https://github.com/tonsky/FiraCode and `set macligatures` and the app would straight up crash or show some weird rendering artifacts while typing out the ligatures.

Some fairly easy repros:

```
:set guifont=FiraCode-Retina:h14
:set macligatures
:edit example.js
```

Then just type like an arrow function:

```
const example = arg => true;
```

And you should see some weird rendering bugs and probably a crash or two. If not, try other ligatures like `!==` or `===`

Another thing I noticed, not sure if a bug or not (it appears to be in the previous version too so not a result of this branch, but potentially something that could be fixed here), in insert mode with the `|` style cursor, it will end up blinking underneath text. 

example

**Comment by amadeus** [comment]
Found another funky issue with line heights and how they are rendered:

example

It happens on the other side of the powerline, although sometimes doing stuff in the window causes the line to get cropped properly.

**Comment by s4y** [comment]
Okay, a bit closer! The new renderer should also be *even faster* now.

> One small thing I noticed with this latest version, fonts are a bit thinner: (https://github.com/macvim-dev/macvim/pull/858#issuecomment-464962498)

This should now match the current renderer.

> NERDTree in combination with vim-devicons works almost perfect, except for the rendering issue on the cursor line, where the folder icon gets clipped. (https://github.com/macvim-dev/macvim/pull/858#issuecomment-465044917)

This is still an issue in the current patch, but I can work on it soon. It's also partly broken in the old renderer: the icons render OK, but moving the cursor down the column to the right of the icons erases the parts that hang into that column.

(Details: The glyphs are wider than a cell but not double-width, so the first cell gets drawn in full (background, then foreground) and then the cell to the right gets drawn in full (background, then foreground). The righthand cell's background is drawn over the glyph. I think the answer is to draw the backgrounds in one pass, then the foregrounds in another pass.)

> Every once in a while, a tiny artifact will appear, in roughly the same-ish location. It looks like a dead pixel but I can confirm its not since (a it comes through on screenshots) and be it follows the window when I move it around. If I scroll the document it goes away (https://github.com/macvim-dev/macvim/issues/796#issuecomment-464949586)

This _should_ be fixed, want to give it another shot?

> Ok - I did find some pretty serious bugs. I normally use Source Code Pro as my main font, but I was messing around with https://github.com/tonsky/FiraCode and set macligatures and the app would straight up crash or show some weird rendering artifacts while typing out the ligatures. (https://github.com/macvim-dev/macvim/pull/858#issuecomment-465950526)

The crashes should be fixed, and rendering should now be similar to shipping MacVim, which is also a little bit broken (ligatures may have some parts drawn as individual characters while you edit them). I think the behavior in this PR is close enough to the current state for now, but I have thoughts on how to fully fix it in the future.

> Found another funky issue with line heights and how they are rendered: (https://github.com/macvim-dev/macvim/pull/858#issuecomment-466552738)

Fixed!

> EDIT: Also been noticing that non native full screen, when activated on my iMac, seems to get stuck in a weird way where the window isn't full screen, but it just renders a blank screen… (https://github.com/macvim-dev/macvim/pull/858#issuecomment-466552738)

I believe this is fixed too, want to give it another try?

**Comment by amadeus** [comment]
Woots! Giving it a try!

**Comment by amadeus** [comment]
So non-native fullscreen works when you go into it via `:set fu`, but doing `:set nofu` completely hard crashes macvim it seems.

**Comment by chdiza** [comment]
I've just tried this on Mojave for about 1 minute, and I don't see the NNFS crash that @amadeus mentioned.

**Comment by chdiza** [comment]
Whoops, never mind.  There's the crash!

I didn't see it at first because I have S-Cmd-F bound to a VimL function that does some preparatory work before it calls `:set nofu`.  For some reason that doesn't crash, but if I manually type `:set nofu` it does.

**Comment by s4y** [comment]
I'm hacking on this right now. The crash happens because, while exiting full screen, `-setMaxRows:columns:` may be called first, then drawing commands arrive which point out of bounds 😕. I currently have the following approaches in mind:

- Validate/filter drawing commands.
- Have `grid_cell()` (or a new function like `grid_cell_safe()`) return a pointer to a scratch cell when it's called with out-of-bounds coordinates.
- Call `setMaxRows:columns:` when the draw commands switch to the new size, not sooner.

…but I'm still thinking through it.

**Comment by s4y** [comment]
Hey all, mind re-testing? The crash should be fixed.

`setMaxRows:columns:` gets called a few different ways, and while I'm convinced it's possible to shuffle things so that it's aligned with the draw commands coming from Vim, I'm not going to try right now 🙂.

**Comment by s4y** [comment]
Just did a little bit of cleanup. I'll leave this PR as a draft until I get _some_ feedback, but otherwise it may be ready for review!

**Comment by pirminis** [comment]
@s4y is it possible to install this version from pull-request using brew? or it is possible only by building macvim yourself?

**Comment by chdiza** [comment]
@s4y I've been playing a bit with this and I haven't seen the crash yet.

There are however some odd visual artifacts when moving in to non-native fullscreen.  I think I might have mentioned this before in some other thread, but: I can see, very briefly, a rendering of the contents of the MacVim window intermediate in size between where one starts and the full-blown fullscreen.  E.g., I can see very briefly Vim's menubar occupying half of the MacBook's screen width, even though when non in fullscreen it takes up about a quarter and when in fullscreen it takes the whole width. 

(And curiously, that same menubar is *much* higher up on the screen during this "flash" than at the start point, enough so that I believe that `&lines` is somehow being temporarily reset to something much smaller.  I.e., my MacVim window is 50 `&lines` tall, I hit the key chord to enter NNFS, I can briefly see a Vim menubar (&ls=2) that's so high up on the screen that I suspect that &lines got quickly set to somewhere between 15 and 20, and then I end up in NNFS.)

I should mention this is with `MMFullScreenFadeTime` set to 0.  (I despise animations and fadeout/in.) When I get a chance I'll adjust that and see if it makes a difference.

**Comment by s4y** [comment]
@chdiza Good catch. Let me know how it looks now. There was a bug in the resize process that could've resulted in a glitch, and that should be fixed now. There's still a flicker, but it has the same root cause as the flicker that *currently* happens when entering or leaving NNFS with `MMFullScreenFadeTime` set to 0. I'd be interested in fixing that in the future.

**Comment by chdiza** [comment]
@s4y OK, I've been playing with the latest edition.  The strange artifact seems to be *much* less severe, thanks!  It might even be identical to "current" behavior, but I keep getting the impression that the transition into NNFS is now ever so slightly delayed.  That might just be my eyes playing tricks on me.

BTW, thanks for all your work on this.  Non-native fullscreen in MacVim for me is an *absolute necessity*; without it I'd just use console vim inside iTerm2, which itself has a great non-native fullscreen mode.

**Comment by s4y** [comment]
@chdiza Thanks, I appreciate it! I would eventually like to make the transition into and out of NNFS atomic, so that it switches in a single frame with no intermediate flashes. I was able to see a slight (~1 frame) delay, and made a couple of tweaks that might help.

**Comment by s4y** [comment]
I may look over the code more myself, but overall I think this is in a good state to be reviewed (cc @ychin) 😬.

**Comment by chdiza** [comment]
@s4y Did something just change that I should now play around with?

**Comment by chdiza** [comment]
Arggh, sorry, I forgot about the last part of your post.  Will test today.

**Comment by chdiza** [comment]
@s4y I'm sorry to report that I think this PR has undone the fast buffering of output of the `:!` command that had been added to MacVim recently in #840.

**Comment by s4y** [comment]
@chdiza Sorry, I just rolled that tweak back because it degraded performance in other situations :/. I also saw your comment about the perf regression from #840, hmm, I'll look into _that_ later today.

---

My theory is that the fullscreen transition could be *slightly* slower (about an extra frame — unfortunately only noticeable with `MMFullScreenFadeTime` set to `0`) because it currently involves a couple of full redraws. I can think of ~three optimizations which could help:

- Skip drawing the backgrounds of blank lines or large parts of lines with no content.
- Make sure that the view only redraws _once_ during a fullscreen transition.
- Don't redraw immediately when resized (i.e. use `layerContentsRedrawPolicy`).

**Comment by s4y** [comment]
@chdiza All right, actually going to put this down now, but could you test those cases again? I just did some quick profiling and found+fixed a couple of big bottlenecks.

**Comment by chdiza** [comment]
I'll test this later today when I get a chance.  And I'll also try them out with the FadeTime set to some nonzero but still small level.

**Comment by chdiza** [comment]
I've played around for a bit and don't seem to be able to spot a difference since the last time I tested, at least wrt flashing.

There does seem to be a regression when coming out of NNFS if I enlarged the font while still in NNFS.  The MacVim window seems to want to come out of NNFS at coordinate 0,0 (northwest corner of MacVim on the northwest corner of the screen), and then there is a noticeable delay while it then "bumps down" to coordinate (0,22) to stay off the macOS menubar.  I don't remember seeing this before.

**Comment by s4y** [comment]
@chdiza Ah, sorry, I was referring to your comment about the fast buffering regression (https://github.com/macvim-dev/macvim/pull/858#issuecomment-490161270). Does that seem any better? I can check out NNFS later today, hopefully.

**Comment by chdiza** [comment]
@s4y OK, I'm getting confused.  Tomorrow when I get a chance I'll look at the buffering issue.

**Comment by s4y** [comment]
OK, great.

Re. the window-bumps-down issue (https://github.com/macvim-dev/macvim/pull/858#issuecomment-490264027), I see that in shipping MacVim, too, so this renderer may just have different performance characteristics than the shipping one, and entering/exiting fullscreen may be slightly slower. I'm not done optimizing it! …but if this is better for most cases, then I'd really like to have it reviewed and landed in (close to) its current state, and then keep improving it, instead of growing and changing the initial PR, assuming that seems reasonable to you and the maintainers.

(I.e. I'm trying to avoid changing it too much while it's in review, but there's a lot of room to optimize this renderer and I'm very much planning to.)

**Comment by chdiza** [comment]
> then I'd really like to have it reviewed and landed in (close to) its current state, and then keep improving it, instead of growing and changing the initial PR, assuming that seems reasonable to you and the maintainers.

It does seem totally reasonable to me.

**Comment by s4y** [comment]
Great, CI passes! The rest of this comment is a call for some quick testing of something performance-related I ran into this morning, if anyone feels like it, followed by some background.

I'm hoping that folks with a range of hardware (MacBook Airs to iMac Pros) and, critically, at least some running a macOS version _before_ Mojave, could try this:

- Check out the experimental commit 3a31b15aee3d758238c77f717727e3ef79115206 (either by [downloading a snapshot](https://github.com/macvim-dev/macvim/archive/3a31b15aee3d758238c77f717727e3ef79115206.zip), or by running `git fetch 3a31b15aee3d758238c77f717727e3ef79115206 && git checkout 3a31b15aee3d758238c77f717727e3ef79115206`.
- Build and run.
- Open a file (larger is better; at least a few screenfuls of text) and see how MacVim performs. Try the benchmark command below (`let g:profstart…`).
- Now, switch to the current PR (43c4528c56ed070ed4a98fbf69db021c3d0de555) and repeat. How does performance compare?

- - -

Last night, I noticed that _deleting_ a call to `self.wantsLayer = YES` (which I added to improve performance when building with a pre-Mojave SDK, before layer backing became the default) made this benchmark command that @ychin posted in #746 run ~10x as fast:

```
let g:profstart=reltime() | for i in range(1,30) | exec "normal \<C-E>" | redraw | endfor | echo reltimestr(reltime(g:profstart)) . " seconds"
```

I deeply questioned the performance characteristics of layers until I finally noticed (in Instruments) that without `wantsLayer`, `drawRect:` always got called via `+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke`, but with `wantsLayer` that function was absent from the call stack.

When an NSWindow is marked as needing display, the window calls (undocumented) `+[NSDisplayCycle currentDisplayCycle]`, which calls `+[CATransaction NS_setFlushesWithDisplayRefresh]`. _All_ views wait to draw until the system wants to output a new frame to the screen, instead of drawing right away on the next run loop cycle. In MacVim, there's time for many more draw commands from the backend to come in, followed by a single `drawRect:`, versus a `drawRect:` for each batch of commands. This saves a ton of time.

This may actually be an AppKit bug, and I want to file a radar for it when I have a chance: When a layer-backed view needs to be displayed, it should also call `+[CATransaction NS_setFlushesWithDisplayRefresh]`.

The simplest workaround I found is to poke the NSWindow in `-[MMWindowController processInputQueueDidFinish]`, like this:

```objc
if ([self.window respondsToSelector:@selector(_postWindowNeedsDisplayUnlessPostingDisabled)])
    [self.window performSelector:@selector(_postWindowNeedsDisplayUnlessPostingDisabled)];
```

…which makes MacVim perform identically with and without `wantsLayer` on Mojave, when built with the 10.14 SDK. I think explicitly requesting a layer could still be worthwhile on older macOS (and if anything uses layers in the future), but I'm leaning on you, the reader, to help figure that out.

**Comment by amadeus** [comment]
I am running an iMac (2015) and the difference running that benchmark was negligible on both branches. Enabling or disabling syntax made the biggest difference, and also depending on the lines in view, would also make a bigger difference.

For example, the file i was using, was JS, and from the top of the screen, I would reliably get about 0.2 seconds, as I kept running the profile, and those initial lines moved out of view, the perf would improve to about 0.1 seconds.

This happened in both this PR and the other branch, fairly consistently.

With syntax highlighting disabled, I would get performance of around 0.01 seconds consistently

**Comment by ychin** [comment]
Sorry I have been absent for the last month or so. I will take a look and try it out!

**Comment by s4y** [comment]
@ychin Yay, I appreciate it!

@amadeus Thank you! OK, I'm glad they perform similarly, which sounds right for Mojave. On earlier macOS (even 10.13), I hope that the experimental change (which I'm just going to add to this PR; the instructions above still point to the right thing). However, 0.1 vs 0.01 is a _big_ difference. Is that really with syntax highlighting off vs on? If so, it'd be amazing if you could share a screenshot or screen recording — maybe something about your colorscheme is hitting a slow case. I also bumped up the number of iterations in the copy-and-paste-able benchmark to get less noisy data.

**Comment by chdiza** [comment]
> The buffering issue seems to have been repaired in my limited testing.

After further playing, it seems that this is still an issue.  It's better than it was when I first reported it, but comparing it to how MacVim works without this PR, it's noticeably slower.

**Comment by s4y** [comment]
@chdiza Hmm, OK.
- Which commit are you testing? (The most recent ones have some optimizations.)
- Which macOS version, screen resolution (and retina/non-retina), and hardware are you using?
- If possible, could you upload screen recordings showing the difference?

This doesn't match my testing and I want to find out why! For me, both the shipping version of MacVim and the version in this PR end up being limited by the backend when running a command like `:!hexdump /dev/urandom`.

**Comment by chdiza** [comment]
> Which commit are you testing? 

I've lost track!  I'll try again when I get the chance.

> Which macOS version, screen resolution (and retina/non-retina), and hardware are you using?

10.14.4, 1280x800, non-retina, MacBookPro 9,2.

**Comment by eirnym** [comment]
it's quite strange. build has been failed. What have I done wrong? I can clean up and run again if required.
```
$ cd src
$ ./configure --enable-pythoninterp=dynamic --enable-python3interp=dynamic
[...]
$ make
[...] failed build
$ make
[...] output is attached
```
[output of failed make](https://github.com/macvim-dev/macvim/files/3183831/make.txt)

**Comment by eirnym** [comment]
@s4y Wow! it works as a charm! I see no artefacts with the output of [rndgen tool](https://bitbucket.org/eirnym/bin/src/master/dev/rndgen):

`$ rndgen -a --amount 1000 120`

**Comment by juliuszint** [comment]
Ive been working with this patch now for over 2 weeks at least 5 hours a day with no issues. Im running it on a MacBook Pro (2017), macOS 10.14.4, connected to a 4k external display. 

There is only one thing different from the normal version of MacVim. Whenever i run FZF it seems that the cursor is jumping around (just visually). [This](https://www.dropbox.com/s/6koyiv47jb3dzmo/Screen%20Recording%202019-05-23%20at%2011.07.43.mov?dl=0) screen recording shows the flickering and when you single step through the video you can catch some cells getting drawn with white background.

Thanks for your work!

File: src/MacVim/MMWindowController.m [hunk 1]
```diff
@@ -110,6 +110,14 @@ - (void)_setContentHasShadow:(BOOL)shadow; // new Tiger private method
...
 // We want this on Leopard.
 - (void)setBottomCornerRounded:(BOOL)rounded;
+
+// Private API which waits until the next frame to commit the current
+// CATransaction. Without it, a view which is set to need display will draw as
+// soon as the thread returns to the event loop; potentially drawing much more
+// frequantly than they'll appear on the screen. This method is called
+// automatically by AppKit when a *window* needs display, but not when a view
+// subtree with `wantsLayer = YES` needs display, which may be a macOS bug.
+- (void)_postWindowNeedsDisplayUnlessPostingDisabled;
```
Comment (ychin) [inline src/MacVim/MMWindowController.m]: I'm a little nervous about adding dependencies on private APIs and prefer if we could find a way around it. @s4y can you elaborate a little more why this was added? Did it improve performance a lot? I did a brief test and didn't see a difference and wonder under what conditions you saw an improvement.

File: src/MacVim/MMCoreTextView.m [hunk 2]
```diff
@@ -626,7 +669,7 @@ - (BOOL)mouseDownCanMoveWindow
 
 - (BOOL)isOpaque
 {
-    return YES;
+    return self.layer == nil || self.defaultBackgroundColor.alphaComponent == 1;
```
Comment (ychin) [inline src/MacVim/MMCoreTextView.m]: I think this is currently breaking the `transparency` setting. Just do `set transparency=50` and compare the screenshots. If you use colorscheme `industry` (which has a black background) and overlay it on a white background, and you screencap it, the color should be exactly 0.5 / 128. With this change I think there is some double blending going on.

Also, in pre-Mojave builds (<=10.13), transparency just stopped working it seems. The background no longer shows through.

The current transparency support is a little brittle and has different behaviors under Mojave due to the different renderer used (see #805), so you may want to double-check that.

File: src/MacVim/MMCoreTextView.m [hunk 3]
```diff
@@ -127,26 +126,98 @@ - (void)drawInvertedRectAtRow:(int)row column:(int)col numRows:(int)nrows
...
+
+static void grid_resize(Grid *grid, int rows, int cols) {
+    const int oldSize = grid->rows * grid->cols;
+    const int newSize = rows * cols;
+    if (rows == grid->rows && cols == grid->cols)
+        return;
+    if (grid->cells == NULL) {
+        grid->cells = calloc(rows * cols, sizeof(GridCell));
+    } else {
+        if (cols < grid->cols) {
```
Comment (ychin) [inline src/MacVim/MMCoreTextView.m]: I believe there is a bug here. If you let's say resize from 1 row x 5 cols to 5 rows x 1 col, `newSize` will be the same as `oldSize`, and the old data won't get properly cleared out. Basically, `grid->cells[1..4]` will have junk data (they should be zero), while `grid->cells[0]` is correct (it has the value of first row first column).

I think this bug doesn't manifest itself because Vim is just going to redraw everything but we should probably fix this in case other code tries to use it later.

**Comment by eirnym** [comment]
@s4y How's going? there's long time passed and no updates.

**Comment by eirnym** [comment]
@s4y and could I ask you to update your branch with the latest changes?

**Comment by kcmannem** [comment]
would love to see this merged in.

**Comment by s4y** [comment]
Thanks for the reminder. Just rebased, I'll revisit the remaining issues shortly.

**Comment by amadeus** [comment]
And you fixed xcode 11 builds, bless!

File: src/MacVim/MMCoreTextView.m (hunk 3 above)
Comment (s4y) [reply src/MacVim/MMCoreTextView.m]: Fixed and simplified.

File: src/MacVim/MMWindowController.m (hunk 1 above)
Comment (s4y) [reply src/MacVim/MMWindowController.m]: It looks like this bug is fixed as of macOS 10.15! I updated the workaround to remove the private API dependency and only run on 10.14 and older.

On 10.14, the difference is huge when using this test:

```
let g:profstart=reltime() | for i in range(1,100) | exec "normal \<C-E>" | redraw | endfor | echo reltimestr(reltime(g:profstart)) . " seconds"
```

Without the workaround, drawing happens many times per frame:

1.613321 seconds

With the workaround, the extra draws are skipped:

0.028653 seconds

**Comment by eirnym** [comment]
@s4y hey, could you merge master to your branch/rebase on as many changes were changed in Vim base?

**Comment by amadeus** [comment]
It looks like it was rebased yesterday, it should be very up to date, minus maybe a snapshot commit or two

**Comment by eirnym** [comment]
Thank you, probably I've missed it. Rebase is kind-a invisible in `git`

**Comment by amadeus** [comment]
The way you can tell in github - is that the list of commits will move in the comment stream. If there are no comments, then it won't be obvious, but in this case - the commits all moved to the end of this comment stream, which is how I knew

**Comment by eirnym** [comment]
I agree with you

I'd prefer to open a graph to see how branches are related to each other. However, I've seen this feature in few other systems like GitLab (not sure about current version).

**Comment by nooks** [comment]
image
Font bug folders NERDTree

**Comment by randrew** [comment]
Sorry for the drive-by comment. I was just looking through issues with no particular goal in mind, and noticed something subtle and interesting about the screenshot above. The MacVim window on the left seems to have some strange colorspace or compositing issue going on -- the background fill color has some kind of dithering or noise pattern applied to it, while the MacVim window on the right has a solid fill color (and appears to be correct.)

Is that simply because one window is in the foreground and the other is behind? Or some issue with how the screenshot was captured? Or is that normal in macOS?

**Comment by amadeus** [comment]
@randrew that’s just the window drop shadow being applied on top of the window on the left

**Comment by randrew** [comment]
Sorry if this is too far off-topic. I'm curious about what's going on. If you would like me stop, I will.

It seems to extend all the way to the left edge of the window, where there doesn't appear to be any drop shadow effect:

msedge_oDK1HBJTBC

I took a screenshot of two overlapping Terminal.app windows in a similar arrangement, running on 10.15:

Screen Shot 2020-02-28 at 2 55 03 PM

The dithering is apparent in both windows. I'm wondering if this is caused by the compositing and/or rastierzation colorspace being different, depending on which toolkit it is being built with or which font rendering APIs are being used.

**Comment by amadeus** [comment]
Interesting bug with lots of terminal output from vim fugitive, not sure if it's related to this patch or not, but figured I would start with it here:

[video example](https://cdn.discordapp.com/attachments/365662117191352320/690276108993822972/screencast_2020-03-19_12-08-46.mp4)

Seem's there is lots of injected blank lines between a lot of the output when it comes in noisily. Also, any update on when we can get this merged? I can't use macvim without it, and would love to not be managing a custom build all the time.

File: src/MacVim/MMCoreTextView.m (hunk 2 above)
Comment (s4y) [reply src/MacVim/MMCoreTextView.m:674]: Fixed the double blending in e5c2fba9542161d25fe1fd74118e409fea0fb69a. I don't have access to a 10.13 machine to test right now — I may try to set up a VM, but for the moment it's safest to assume that I only have access to 10.14 and 10.15, unfortunately.

**Comment by s4y** [comment]
@nook-scheel Hmm, it looks like everything is rendered in the base font; no styles like bold. I haven't seen that happen. Could you share some details like OS version and specifically what font you're using?

**Comment by s4y** [comment]
@randrew FWIW, I see this too! It's most visible if I zoom in and turn my screen brightness up. Perhaps it's worth tracking as a separate issue after this lands?

**Comment by eirnym** [comment]
It would be a huge improvement when it land eventually. I'd agree with. minor possible disadvantages and drawbacks to make it land as fast as it can

**Comment by amadeus** [comment]
Here's a funky bug I am seeing with emoji with current latest updates:

example

**Comment by s4y** [comment]
@amadeus Both should be resolved now. Ligatures should also work significantly better.

**Comment by amadeus** [comment]
Looks like it works well!

Small nit - is it possible for the emoji to fit better inside their double-wide space?

image

**Comment by s4y** [comment]
@amadeus This seems to be up to the font and really depend on size. The difference between Menlo at 8pt and 9pt is particularly obvious:

Screen Shot 2020-04-10 at 5 25 57 PM Screen Shot 2020-04-10 at 5 25 54 PM

…and it looks like native macOS text rendering straight-up ignores fixed width when emoji are involved:

Screen Shot 2020-04-10 at 5 34 53 PM

Right now I don't see any good knobs to tweak 😕, but I'm open to ideas.

**Comment by s4y** [comment]
Worth noting that, aside from the font issue (https://github.com/macvim-dev/macvim/pull/858#issuecomment-573677304) that I haven't been able to reproduce as of yet, I think this is in a good place.

**Comment by eirnym** [comment]
It's a huge success for emoji rendering!

**Comment by garrettf** [comment]
I want to give you a huge thankyou for putting this out. I've been using this branch in my day-to-day for a year now without many issues, and would love to support the improvements.

I recently rebased and encountered an issue that may be similar to this: https://github.com/macvim-dev/macvim/pull/858#issuecomment-573677304

Compare how font variants are selected between an old SHA:
Screen Shot 2020-05-06 at 1 06 04 PM
And the current 58fdbec:
Screen Shot 2020-05-06 at 1 06 02 PM

It appears to be selecting different fonts for bold and italic, but not the correct fonts based on the selected `guifont`.

**Comment by s4y** [comment]
@garrettf Does this latest commit change anything?

Interesting, Monaco doesn't have bold and italic variants, and as far as I can tell shipping MacVim will use the base font in that case. I think this branch had a bug where the font variant picking code would try to use `nil` instead, which could result in unexpected behavior. I'm not sure what bold and italic font you were seeing before (and am open to theories), but now the behavior _should_ match stable.

**Comment by garrettf** [comment]
My mistake, the `guifont` in the sample was Menlo, not Monaco. 

@s4y All good now! Thanks for the speedy fix.
Screen Shot 2020-05-06 at 3 28 52 PM

Pulling out that example again:

Screen Shot 2020-05-06 at 3 34 58 PM
This looks like Arial Italic to me. I haven't dug deeply into the source, but potentially `fontWithDescriptor` was defaulting to the first italic font on my system, alphabetically? Very strange. 

Screen Shot 2020-05-06 at 3 35 02 PM
This looks like Monaco to me, no idea what happened there.

But I'm glad it's all fixed :)

**Comment by s4y** [comment]
Rebased.

**Comment by s4y** [comment]
@garrettf Nice \o/. And thanks for the detailed reports 🙂,

**Comment by s4y** [comment]
I just realized that this has been sitting idle for a bit. Is there anything I can do to help it along? I realize it ended up being a big/involved change, but I'm pretty happy with the result (and open to pushback/changes, too).

**Comment by s4y** [comment]
Just rebased for good measure. Otherwise no changes.

**Comment by eirnym** [comment]
@s4y @ychin Could this renderer in current state be integrated as an _experimental_ renderer? something like with information that "no warranty" for time being? This will give others an opportunity to use it and report issues for, so development will be a bit faster?

**Comment by s4y** [comment]
@eirnym It would be possible to refactor it into an extra/experimental renderer, but I genuinely think that this change is in a good place to launch! AFAIK there haven't been any bug reports since my last push in May, there are no known issues, and I'm available to help sort out any bugs that crop up if this were launched.

I also have ideas for followup changes around both code cleanup in how rendering works and making rendering _even faster,_ and that's trickier when there are ~4 rendering code paths all being actively used.

**Comment by s4y** [comment]
Oh, and the tests were failing before this rebase for reasons unrelated to this change — I think master was just in a bad place the last time I rebased.

**Comment by eirnym** [comment]
News sound great! Nevertheless, I'd make this as an experimental renderer as it could cause issues on environments was never tested here. Just to make sure that a user has a fallback to their previous renderer which is working for him/her

**Comment by amadeus** [comment]
Given this PR is over a year old, and we are quickly approaching the release of macOS 11, it would be nice to get this merged in ASAP. It can always be reverted if it creates issues for people. Furthermore, people can always download a previous build if this new one doesn't work. Or maybe just release it as a beta build to get more eyes on it?

**Comment by ychin** [comment]
Yeah that's fair. I think this PR suffered from me paying infrequent attention to it and I haven't been keeping up to date to its development. I'll take a pass through the change and the discussion thread.

**Comment by nuc** [comment]
Tried it out locally, and it seems quite good. Looking forward to see this PR merged 🤞

**Comment by pirminis** [comment]
@ychin when will this wonderful PR be merged? 😄

**Comment by ychin** [comment]
Hi @s4y and others, sorry for the delays. It took me some time to read through the code and test out the different edge cases. I think this looks pretty good! It's very close to merging but I'm trying to figure a couple things out:

----

❌ Bugs / concerns (high priority):
* Ligatures seem a little broken. Paste this line in: `մեab`, and then call `:set macligatures`. Move your cursor over it, and it will be a little broken.
  * How it should look like:  image
  * It looks like this in the branch: image.
  * When highlighted, it looks like this:  image

❌ Questions on open issues:
* Is https://github.com/macvim-dev/macvim/pull/858#issuecomment-573677304 addressed?
* Is https://github.com/macvim-dev/macvim/pull/858#issuecomment-465044917 (clipping on NerdTree icons) addressed?
* Is the `wantLayer` performance issues resolved on both 10.15 and 10.14 since we removed the private API call (see https://github.com/macvim-dev/macvim/pull/858#discussion_r294250604 and responses)? Unfortunately I upgraded to 10.15 and can't test on 10.14 right now. Just want to make sure 10.14 performance is acceptable.

❓Bugs / Concerns (medium priority):
* I'm a little concerned with the cache usage when ligatures is turned on. The code caches a whole line of text (instead of individual characters) which could grow unbounded (we never clear `characterLines` and `characterStrings`). If you edit a lot of text I think the cache would keep growing and growing because each line is unique. Have you thought about how to resolve that? This is not blocking for now but I think we should fix it post-merge.
* Transparency is still a little broken. Below are screenshots of before/after (with `set transparency=50` / `color desert` / `set cursorline`). I think it has to do with setting `isOpaque` to false. Why is it set that way? (All the below were overliad on top of a white background)
  * No transparency:
    image
  * Transparency 50 (master):
    image
  * Transparency 50 (stateful-renderer) – You can see that the cursorline (1st line) is darker even though it should be lighter:
    image

❓Bugs (low priority):
* The insert mode cursor size is double-width when it's over a full-width character (e.g. 😅) but it shouldn't be.
* Signs icon rendering is a little broken right now. Do `sign define foo icon=/Some/Path.png` and then `sign place 1 line=1 name=foo`, and you will see that the sign is only one column wide, while it should be 2 columns.

Random observations:
* Font substitution seems to be working a little differently. I think it's due to how we now draw CTLine instead of manually looking up a substitution font and drawing glyphs for it. For example, this text will look different between old and new: `、。`, and I think it's due to a different font being used. I don't think it's a big deal, and `guifontwide` actually doesn't work under CoreText renderer anyway (both before and after this change).
* Composing characters seem to work a little differently now. E.g. `a゙` seems to render differently, but the new code seems to match macOS's native rendering which is good.

---

Can we try to address at least the ❌ parts? I know some people really want this merged, but let's make sure the glaring bugs are addressed first. I would like to get to the ❓ parts as well, but I'm ok with merging this without those fixed but we should fix those soon after merging.

Once we get this to a good spot we should probably squash the changes as well as it contains a lot of commits that are no longer relevant.

@eirnym, regarding https://github.com/macvim-dev/macvim/pull/858#issuecomment-656572929, I don't think we should ship this as an experimental renderer, mostly because it changes quite a few places. It's quite tricky to ship this as a standalone path unless we refactor the PR to add back all the previous code paths which would be really messy. We should just make sure to fix up all the current issues.

---

Again, sorry for the slow turnaround time. I'll try to be more prompt to reply to the responses to my questions and feel free to ping me if I don't respond to updates in say a week.

**Comment by juliuszint** [comment]
>     * Is [#858 (comment)](https://github.com/macvim-dev/macvim/pull/858#issuecomment-465044917) (clipping on NerdTree icons) addressed?
> 

This issue is fixed.

**Comment by ychin** [comment]
Pinging @s4y. If I don't see a response I'll start working on fixing up the branch.

**Comment by s4y** [comment]
Excuse me for the delay!

> ❌ Bugs / concerns (high priority):
> * Ligatures seem a little broken. Paste this line in: `մեab`, and then call `:set macligatures`. Move your cursor over it, and it will be a little broken.

I still need to work on this some more. No good answer yet and open to ideas.

> ❌ Questions on open issues:
> * Is the `wantLayer` performance issues resolved on both 10.15 and 10.14 since we removed the private API call (see [#858 (comment)](https://github.com/macvim-dev/macvim/pull/858#discussion_r294250604) and [#858 (comment)](https://github.com/macvim-dev/macvim/pull/858#issuecomment-491517451))? Unfortunately I upgraded to 10.15 and can't test on 10.14 right now. Just want to make sure 10.14 performance is acceptable.

It should be, yes! The private API call was replaced with [this](https://github.com/macvim-dev/macvim/blob/a4bc7fd3d780237e9b0ccd233762e405882f8c70/src/MacVim/MMWindowController.m#L788-L800).

> ❓Bugs / Concerns (medium priority):
> 
> * I'm a little concerned with the cache usage when ligatures is turned on. The code caches a whole line of text (instead of individual characters) which could grow unbounded (we never clear `characterLines` and `characterStrings`). If you edit a lot of text I think the cache would keep growing and growing because each line is unique. Have you thought about how to resolve that? This is not blocking for now but I think we should fix it post-merge.

`characterStrings` is bounded-ish because it only ever represents the strings found in a single cell. You're right about `characterLines`… I swapped in an `NSCache`; does that seem reasonable?

> * Transparency is still a little broken. Below are screenshots of before/after (with `set transparency=50` / `color desert` / `set cursorline`). I think it has to do with setting `isOpaque` to false. Why is it set that way?

This was an issue with blending modes; should be identical now. Let me know? With layer backing, if `isOpaque` is set to false, then the view will be opaque and you won't be able to see through it to other windows.

> 
> ❓Bugs (low priority):
> 
> * The insert mode cursor size is double-width when it's over a full-width character (e.g. 😅) but it shouldn't be.
> * Signs icon rendering is a little broken right now. Do `sign define foo icon=/Some/Path.png` and then `sign place 1 line=1 name=foo`, and you will see that the sign is only one column wide, while it should be 2 columns.

Both fixed!

> Once we get this to a good spot we should probably squash the changes as well as it contains a lot of commits that are no longer relevant.

Definitely; I wasn't sure how you wanted to approach this, but I'm in favor of squashing!

**Comment by gorkunov** [comment]
Found interesting thing. I'm using font `Jetbrains Mono` and currently it looks different on this branch and original macvim. With faster renderer it looks a bit odd (too much horizontal space between symbols).
However if I switch to `Menlo` - it looks the same in both versions.

**Comment by s4y** [comment]
> Found interesting thing. I'm using font `Jetbrains Mono` and currently it looks different on this branch and original macvim. With faster renderer it looks a bit odd (too much horizontal space between symbols).
> However if I switch to `Menlo` - it looks the same in both versions.

@gorkunov Could you share screenshots and the specific font + size you're using? They look the same to me.

**Comment by gorkunov** [comment]
Screenshot 2020-09-24 at 15 58 54@2x

that how JetBrains looks like on my build. It seems something if worng not with horizontal space but with vertical

**Comment by gorkunov** [comment]
compare with menlo (with is almost the same).

**Comment by s4y** [comment]
@gorkunov Could you please share screenshots of both the new and the old appearance, for comparison?

**Comment by gorkunov** [comment]
this is Jetbrains on original macvim
Screenshot 2020-09-24 at 16 22 13@2x

**Comment by amadeus** [comment]
This looks related to this issue: https://github.com/macvim-dev/macvim/issues/977 which is confusing to me why it would effect you now since the changes were related to master.

Try playing with the `linespace` prop to fix it

**Comment by nook-scheel** [comment]
WHEN?

**Comment by s4y** [comment]
> ❌ Bugs / concerns (high priority):
> 
> * Ligatures seem a little broken. Paste this line in: `մեab`, and then call `:set macligatures`. Move your cursor over it, and it will be a little broken.

@ychin I *believe* my latest commit resolves this, but it's very possible I've missed some cases. Fortunately not a terribly complicated fix. What do you think? Please try to break it!

I believe that's the last outstanding issue (aside from squashing, which I'll gladly do when you're ready — I just need to write one commit message to summarize this change 🙂).

**Comment by s4y** [comment]
And… squashed!

**Comment by ychin** [comment]
Hi @s4y sorry for the delay but I'm still finding one issue with it. I haven't been able to look closer into why that's the case yet, but I suspect is a bad interaction with the cache:

1. After you call `set macligatures`, and then paste in this line:
   ```
   😀😨
   ```
   You will notice that the 2nd emoji character keeps jumping around.

Other than mostly looks good, but still need to take a closer look at the NSCache implementation.

Also, thanks for squashing! I think I wasn't clear and I was hoping we only squash when the entire review is signed off as I wanted to diff the latest changes you did, so for future commits can you only squash in the end?

**Comment by s4y** [comment]
@ychin Oof, good catch. I see the problem and I'll try to land a fix shortly. For the moment — unsquashed!

**Comment by s4y** [comment]
@ychin re. https://github.com/macvim-dev/macvim/pull/858#issuecomment-713749037: I believe this is fixed now!

**Comment by eirnym** [comment]
@ychin is something left to fix in this branch to launch this renderer at least as a beta?

**Comment by ychin** [comment]
@s4y The pull request looks good! Sorry for the delay again. Please squash and I'll merge.


---

One minor issue I found has to do with underline rendering. Right now, an empty space would not get the underline drawn. To see a quick repro, you can do `set ft=Markdown`, and then paste in the following line:

```Markdown
[this is a test](https://github.com/macvim-dev/macvim)
```

The whole "this is a test" line should have underline, but in your change, the spaces wouldn't. I think it's a small bug in `setString:` where you just need to make sure the `if ([substring isEqualToString:@" "])` early out makes sure to set the `sp`, `fg`, and `textFlags` on the cell.

I'm ok with merging this without the fix, but it should also be a one line fix.

---

I think we really need better tests for this… Currently I have to go through all known renderer features and make sure they work but after this change merges we should look into better ways to automate this to prevent regressions in the renderer.

Thanks for the work and patience!

File: src/MacVim/MMCoreTextView.m [hunk 4]
```diff
@@ -1708,529 +1417,121 @@ - (void)batchDrawData:(NSData *)data
...
+    __block size_t cells_filled = 0;
+    [string enumerateSubstringsInRange:NSMakeRange(0, string.length)
+                               options:NSStringEnumerationByComposedCharacterSequences
+                            usingBlock:^(NSString *substring, NSRange substringRange, NSRange enclosingRange, BOOL *stop) {
+        GridCell *cell = grid_cell_safe(&grid, row, col + cells_filled++ * (wide ? 2 : 1));
+        GridCellInsertionPoint insertionPoint = {0};
+        if (flags & DRAW_TRANSP)
+            insertionPoint = cell->insertionPoint;
+        if ([substring isEqualToString:@" "]) {
+            *cell = (GridCell){ .bg = bg, .insertionPoint = insertionPoint };
```
Comment (ychin) [inline src/MacVim/MMCoreTextView.m:1435]: Need to set the other variables such as `fg`/`flags`/`sp` as well to make e.g. underline draw properly.

**Comment by s4y** [comment]
@ychin All set! I committed the underline fix as 2ef8f65e7197b10e031b6069479a0272ec88dfc8 for posterity, then squashed.

**Comment by s4y** [comment]
@ychin Oh, and…

> I think we really need better tests for this… Currently I have to go through all known renderer features and make sure they work but after this change merges we should look into better ways to automate this to prevent regressions in the renderer.

If you could start documenting the process you go through, I'm very open to helping automate it.

> Thanks for the work and patience!

Same to you!

File: src/MacVim/MMCoreTextView.m (hunk 4 above)
Comment (s4y) [reply src/MacVim/MMCoreTextView.m]: Done.

**Comment by amadeus** [comment]
🙏🙏🙏

**Comment by ychin** [comment]
Alright this is now merged!

> If you could start documenting the process you go through, I'm very open to helping automate it.

Yeah currently MacVim only uses the default Vim unit tests, which aren't enough. I think we need to write up some MacVim-specific `XCTest` and I have a list of tests that I want to add (e.g. input handling, window resizing, etc) along with text rendering. I will ping you when I make that issue/PR if you want to help.

As for the process, it's unfortunately been a little ad-hoc, mostly playing with known edge cases like with/without macligatures, fullscreen (two types) modes, East Asian languages, emojis, different styles, composing characters, and so on. And I have a list of characters/lines consisting of an assortment of those that I just paste in and see if it looks correct. But this is why we need to get automated testing going to not have to rely on ad-hoc testing :)

**Comment by eirnym** [comment]
How to enable this renderer by default?

**Comment by s4y** [comment]
> As for the process, it's unfortunately been a little ad-hoc, mostly playing with known edge cases like with/without macligatures, fullscreen (two types) modes, East Asian languages, emojis, different styles, composing characters, and so on. And I have a list of characters/lines consisting of an assortment of those that I just paste in and see if it looks correct. But this is why we need to get automated testing going to not have to rely on ad-hoc testing :)

I think even having a written list of these would help a ton in the future! (Running through tests manually isn't too bad, figuring out _what_ to test has been the tricky part.)

**Comment by ychin** [comment]
@eirnym As I have mentioned before this is the only renderer now. It's always the default.
